spring:
  application:
    name: auth-service
#  it disabled config server
  config:
    import: "optional:configserver:"
#  it enabled config server and import config from config server
#  config:
#    import: "configserver:http://localhost:7777"